# Generated by Django 3.1.6 on 2021-02-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
